server:
  port: 8080
spring:
  # 邮件发送
  mail:
    host: smtp.qq.com
    username: 2298012215@qq.com
    password: rfrtaklealxlebca
    default-encoding: utf-8
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库   默认 0 的数据库
    database: 0

    #resources:
    #static-locations: classpath:/static,classpath:/public,classpath:/resources
    #password: 123456

  mvc:
    view:
      prefix: /templates/  #前缀
      suffix: .html  #后缀
    #static-path-pattern: /static/**: #配置静态文件
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource        #druid相关配置
    druid:          #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver       #基本属性
      url: jdbc:mysql://127.0.0.1:3306/itripdb?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
      username: root
      password: root          #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    encoding: utf-8
    #thymeleaf end
    mode: html5
    cache: false
    servlet:
      content-type: text/html


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.itrip.beans

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


